import type { Config } from 'tailwindcss';

const config = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  prefix: '',
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      backgroundImage: {
        bannerImage: "url('/images/opengraph-image.png')",
      },
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        'washed-blue-50': 'hsl(var(--washed-blue-50))',
        'washed-blue-100': 'hsl(var(--washed-blue-100))',
        'washed-blue-200': 'hsl(var(--washed-blue-200))',
        'washed-blue-300': 'hsl(var(--washed-blue-300))',
        'washed-blue-400': 'hsl(var(--washed-blue-400))',
        'washed-blue-500': 'hsl(var(--washed-blue-500))',
        'washed-blue-600': 'hsl(var(--washed-blue-600))',
        'washed-blue-700': 'hsl(var(--washed-blue-700))',
        'washed-blue-800': 'hsl(var(--washed-blue-800))',
        'washed-blue-900': 'hsl(var(--washed-blue-900))',
        'washed-purple-50': 'hsl(var(--washed-purple-50))',
        'washed-purple-100': 'hsl(var(--washed-purple-100))',
        'washed-purple-200': 'hsl(var(--washed-purple-200))',
        'washed-purple-300': 'hsl(var(--washed-purple-300))',
        'washed-purple-400': 'hsl(var(--washed-purple-400))',
        'washed-purple-500': 'hsl(var(--washed-purple-500))',
        'washed-purple-600': 'hsl(var(--washed-purple-600))',
        'washed-purple-700': 'hsl(var(--washed-purple-700))',
        'washed-purple-800': 'hsl(var(--washed-purple-800))',
        'washed-purple-900': 'hsl(var(--washed-purple-900))',
        'primary-blue-50': 'hsl(var(--primary-blue-50))',
        'primary-blue-100': 'hsl(var(--primary-blue-100))',
        'primary-blue-200': 'hsl(var(--primary-blue-200))',
        'primary-blue-300': 'hsl(var(--primary-blue-300))',
        'primary-blue-400': 'hsl(var(--primary-blue-400))',
        'primary-blue-500': 'hsl(var(--primary-blue-500))',
        'primary-blue-600': 'hsl(var(--primary-blue-600))',
        'primary-blue-700': 'hsl(var(--primary-blue-700))',
        'primary-blue-800': 'hsl(var(--primary-blue-800))',
        'primary-blue-900': 'hsl(var(--primary-blue-900))',
        'primary-purple-50': 'hsl(var(--primary-purple-50))',
        'primary-purple-100': 'hsl(var(--primary-purple-100))',
        'primary-purple-200': 'hsl(var(--primary-purple-200))',
        'primary-purple-300': 'hsl(var(--primary-purple-300))',
        'primary-purple-400': 'hsl(var(--primary-purple-400))',
        'primary-purple-500': 'hsl(var(--primary-purple-500))',
        'primary-purple-600': 'hsl(var(--primary-purple-600))',
        'primary-purple-700': 'hsl(var(--primary-purple-700))',
        'primary-purple-800': 'hsl(var(--primary-purple-800))',
        'primary-purple-900': 'hsl(var(--primary-purple-900))',
        'Neutrals/neutrals-1': 'hsl(var(--neutrals-1))',
        'Neutrals/neutrals-2': 'hsl(var(--neutrals-2))',
        'Neutrals/neutrals-3': 'hsl(var(--neutrals-3))',
        'Neutrals/neutrals-4': 'hsl(var(--neutrals-4))',
        'Neutrals/neutrals-5': 'hsl(var(--neutrals-5))',
        'Neutrals/neutrals-6': 'hsl(var(--neutrals-6))',
        'Neutrals/neutrals-7': 'hsl(var(--neutrals-7))',
        'Neutrals/neutrals-8': 'hsl(var(--neutrals-8))',
        'Neutrals/neutrals-9': 'hsl(var(--neutrals-9))',
        'Neutrals/neutrals-10': 'hsl(var(--neutrals-10))',
        'Neutrals/neutrals-11': 'hsl(var(--neutrals-11))',
        'Neutrals/neutrals-12': 'hsl(var(--neutrals-12))',
        'Neutrals/neutrals-13': 'hsl(var(--neutrals-13))',
        'brand-washedPurple': 'hsl(var(--brand-washed-purple))',
        'brand-washedBlue': 'hsl(var(--brand-washed-blue))',
        'brand-primaryBlue': 'hsl(var(--brand-primary-blue))',
        'brand-primaryPurple': 'hsl(var(--brand-primary-purple))',
        'brand-dark': 'hsl(var(--brand-dark))',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
} satisfies Config;

export default config;
