name: CI

on:
  push:
    branches: [main, develop, legal-brand-update, update-readme-branding, refactor/postgrest-api]
  pull_request:
    branches: [main, develop, legal-brand-update, update-readme-branding, refactor/postgrest-api]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Run unit tests (Vitest)
        run: yarn test:unit
      - name: Run E2E tests (Playwright)
        run: yarn test:e2e
