name: CI

on:
  push:
    branches: [main, develop, refactor/postgrest-api]
  pull_request:
    branches: [main, develop, refactor/postgrest-api]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Run unit tests (Vitest)
        run: yarn test:unit

      - name: Build
        run: yarn build

      # - name: Run E2E tests (Playwright)
      #   run: yarn test:e2e
